### ISSUE TITLE
Various bugs

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/ocean-subgraph#288]
Fix most of the bugs. Most that i can find anyway
If the issue is checked it means it's done, if it also has :ballot_box_with_check: it means it is also deployed on v4 subgraph

- [x]  :ballot_box_with_check:  pool snapshot spot price is 0 
- [x]  :ballot_box_with_check:  shares, totalShares ( [query ](https://subgraphv4.rinkeby.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=%7B%0A%20%20pool(id%3A%20%220x1e4350063053f2a16ad9f6e5d73ed56d44eb6c73%22%2C%20subgraphError%3A%20deny)%20%7B%0A%20%20%20%20id%0A%20%20%20%20totalShares%0A%20%20%20%20poolFee%0A%20%20%20%20opfFee%0A%20%20%20%20marketFee%0A%20%20%20%20spotPrice%0A%20%20%20%20baseToken%20%7B%0A%20%20%20%20%20%20address%0A%20%20%20%20%20%20symbol%0A%20%20%20%20%7D%0A%20%20%20%20baseTokenWeight%0A%20%20%20%20baseTokenLiquidity%0A%20%20%20%20datatoken%20%7B%0A%20%20%20%20%20%20address%0A%20%20%20%20%20%20symbol%0A%20%20%20%20%7D%0A%20%20%20%20datatokenWeight%0A%20%20%20%20datatokenLiquidity%0A%20%20%20%20shares(where%3A%20%7Buser%3A%20%220x134b4edd7de8ea003e721e7670800ba97d9af1fd%22%7D)%20%7B%0A%20%20%20%20%20%20shares%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)) bugged 
- [x]  :ballot_box_with_check:  no totalShares on snapshot
- [x]  :ballot_box_with_check:  poolTransaction has no datatoken, baseToken

**Comment by kremalicious** [comment]
- `PoolSnapshot` needs the `block` for our pool graph to work, see [Graph.tsx changes](https://github.com/oceanprotocol/market/pull/993/files#diff-bfa53bc483391f5247d5400c61e91598f9474759ea58b26dfb6e1591e35e6fea) (but might be we are not needing the mechanism in there which is a chunked fetching for performance reasons I think)

**Comment by kremalicious** [comment]
In [this query](https://subgraphv4.rinkeby.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=%7B%0A%20%20pool(id%3A%20%220x1e4350063053f2a16ad9f6e5d73ed56d44eb6c73%22%2C%20subgraphError%3A%20deny)%20%7B%0A%20%20%20%20id%0A%20%20%20%20totalShares%0A%20%20%20%20poolFee%0A%20%20%20%20opfFee%0A%20%20%20%20marketFee%0A%20%20%20%20spotPrice%0A%20%20%20%20baseToken%20%7B%0A%20%20%20%20%20%20address%0A%20%20%20%20%20%20symbol%0A%20%20%20%20%7D%0A%20%20%20%20baseTokenWeight%0A%20%20%20%20baseTokenLiquidity%0A%20%20%20%20datatoken%20%7B%0A%20%20%20%20%20%20address%0A%20%20%20%20%20%20symbol%0A%20%20%20%20%7D%0A%20%20%20%20datatokenWeight%0A%20%20%20%20datatokenLiquidity%0A%20%20%7D%0A%7D%0A) all the fees are `0`. Using `did:op:433c71ffc85604727da7e272ea1f63b083c6f8597086fd9d37acdc7d32373976` as test asset so might be it was published with older contracts

**Comment by mihaisc** [comment]
Fees are a todo, because at that time they were constantly in works , you can check this list https://github.com/oceanprotocol/ocean-subgraph/issues/208

**Comment by kremalicious** [comment]
cool, thanks for info. Already excited about all those fee methods in there allowing us to output accumulated fees.

Another thing I couldn't get to work is pool creator liquidity or more precisely NFT owner liquidity, using [this query](https://subgraphv4.rinkeby.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=%7B%0A%20%20pool(id%3A%20%220x1e4350063053f2a16ad9f6e5d73ed56d44eb6c73%22%2C%20subgraphError%3A%20deny)%20%7B%0A%20%20%20%20id%0A%20%20%20%20totalShares%0A%20%20%20%20poolFee%0A%20%20%20%20opfFee%0A%20%20%20%20marketFee%0A%20%20%20%20spotPrice%0A%20%20%20%20baseToken%20%7B%0A%20%20%20%20%20%20address%0A%20%20%20%20%20%20symbol%0A%20%20%20%20%7D%0A%20%20%20%20baseTokenWeight%0A%20%20%20%20baseTokenLiquidity%0A%20%20%20%20datatoken%20%7B%0A%20%20%20%20%20%20address%0A%20%20%20%20%20%20symbol%0A%20%20%20%20%7D%0A%20%20%20%20datatokenWeight%0A%20%20%20%20datatokenLiquidity%0A%20%20%20%20shares(where%3A%20%7Buser%3A%20%220x134b4edd7de8ea003e721e7670800ba97d9af1fd%22%7D)%20%7B%0A%20%20%20%20%20%20shares%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A) and the `shares` are always `[]`. But again might be because of test asset

**Comment by mihaisc** [comment]
keep them coming  , i'll add them in the list in the main description.
